name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: UnitTest
      id: unittest
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: UnitTest
        setup-command: ''
        command: mvn test
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        UNITTEST_RESULTS: "${{steps.unittest.outputs.result}}"
      with:
        runners: unittest
