# Generated by Django 5.2 on 2025-05-20 14:19

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_vessel_board_boardvessel_shot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vessel',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
